---
- name: Harden RHEL/CentOS 8 with OpenSCAP and PCI-DSS
  hosts: all
  become: true
  vars:
    openscap_ds: "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
    profile: "xccdf_org.ssgproject.content_profile_pci-dss"
    report_dir: "/tmp/openscap_reports"

  tasks:
    - name: Install OpenSCAP and dependencies
      ansible.builtin.package:
        name:
          - openscap-scanner
          - scap-security-guide
          - yum-utils
        state: present

    - name: Create report directory on the managed node
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'

    - name: Run OpenSCAP scan
      ansible.builtin.command:
        cmd: "oscap xccdf eval --profile {{ profile }} --report {{ report_dir }}/report-{{ inventory_hostname }}.html {{ openscap_ds }}"
      register: oscap_scan
      changed_when: oscap_scan.rc != 0
      failed_when: oscap_scan.rc not in [0, 2]

    - name: Check if reboot is required
      ansible.builtin.command:
        cmd: "needs-restarting -r"
      register: reboot_check
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Display reboot status
      ansible.builtin.debug:
        msg: "Reboot is required on {{ inventory_hostname }}"
      when: reboot_check.rc == 1

    - name: Create local report directory
      ansible.builtin.file:
        path: "./reports"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Fetch reports
      ansible.builtin.fetch:
        src: "{{ report_dir }}/report-{{ inventory_hostname }}.html"
        dest: "reports/"
        flat: yes
